{{- if eq (.Values.networkPolicy | lower) "enabled" }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ template "zookeeper.client-networkpolicy-name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{ include "zookeeper.labels" . | indent 4  | trim }}
spec:
  podSelector:
    matchLabels:
      {{ include "zookeeper.selector" . | indent 6  | trim }}
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector: {}
    ports:
    - protocol: TCP
      port: {{ .Values.clientPort }}
{{- end }}
