{{- if eq (.Values.networkPolicy | lower) "enabled" }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-networkpolicy
  namespace: {{ .Release.Namespace }}
  labels:
    {{ include "zookeeper.labels" . | indent 4  | trim }}
spec:
  podSelector:
    matchLabels:
      {{ include "zookeeper.selector" . | indent 6  | trim }}
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          {{ include "zookeeper.selector" . | indent 10  | trim }}
    ports:
    - protocol: TCP
      port: {{ .Values.serverPort }}
    - protocol: TCP
      port: {{ .Values.leadElectionPort }}
{{- end }}