apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ .Release.Name }}-pdb
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "zookeeper.labels" . | indent 4 }}
spec:
  selector:
    matchLabels:
      {{ include "zookeeper.selector" . | indent 6  | trim }}
  maxUnavailable: {{ .Values.podDisruptionBudget.maxUnavailable }}
