apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-cs
  namespace: {{ .Release.Namespace }}
  labels:
    {{ tpl .Values.labels . | nindent 4 | trim }}
spec:
  clusterIP: None
  ports:
    - port: {{ .Values.zookeeper.clientPort }}
      name: client
  selector:
    {{ tpl .Values.matchLabels . | nindent 4 | trim }}
