apiVersion: v1
kind: Service
metadata:
  name: {{ template "zookeeper.headless-service-name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{ include "zookeeper.labels" . | indent 4 | trim }}
spec:
  clusterIP: None
  ports:
    - port: {{ .Values.serverPort }}
      name: server
    - port: {{ .Values.leadElectionPort }}
      name: leader-election
  selector:
    {{ include "zookeeper.selector" . | indent 4 | trim }}
