apiVersion: v1
kind: Service
metadata:
  name: {{ template "zookeeper.client-service-name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{ include "zookeeper.labels" . | indent 4  | trim }}
spec:
  clusterIP: None
  ports:
    - port: {{ .Values.clientPort }}
      name: client
  selector:
    {{ include "zookeeper.selector" . | indent 4  | trim }}
